
/**
 * @fileoverview Externs for underscore-1.3.1.js
 * 
 * built with http://www.dotnetwise.com/Code/Externs/index.html
 * see also: http://blog.dotnetwise.com/2009/11/closure-compiler-externs-extractor.html
 * via: http://code.google.com/p/closure-compiler/wiki/FAQ#How_do_I_write_an_externs_file?
 * 
 * @see http://documentcloud.github.com/underscore/
 * @externs
 */

var _ = {
    "VERSION": {},
    "forEach": function () {},
    "each": function () {},
    "collect": function () {},
    "map": function () {},
    "inject": function () {},
    "foldl": function () {},
    "reduce": function () {},
    "foldr": function () {},
    "reduceRight": function () {},
    "detect": function () {},
    "find": function () {},
    "select": function () {},
    "filter": function () {},
    "reject": function () {},
    "all": function () {},
    "every": function () {},
    "any": function () {},
    "some": function () {},
    "contains": function () {},
    "include": function () {},
    "invoke": function () {},
    "pluck": function () {},
    "max": function () {},
    "min": function () {},
    "shuffle": function () {},
    "sortBy": function () {},
    "groupBy": function () {},
    "sortedIndex": function () {},
    "toArray": function () {},
    "size": function () {},
    "head": function () {},
    "first": function () {},
    "initial": function () {},
    "last": function () {},
    "tail": function () {},
    "rest": function () {},
    "compact": function () {},
    "flatten": function () {},
    "without": function () {},
    "unique": function () {},
    "uniq": function () {},
    "union": function () {},
    "intersect": function () {},
    "intersection": function () {},
    "difference": function () {},
    "zip": function () {},
    "indexOf": function () {},
    "lastIndexOf": function () {},
    "range": function () {},
    "bind": function () {},
    "bindAll": function () {},
    "memoize": function () {},
    "delay": function () {},
    "defer": function () {},
    "throttle": function () {},
    "debounce": function () {},
    "once": function () {},
    "wrap": function () {},
    "compose": function () {},
    "after": function () {},
    "keys": function () {},
    "values": function () {},
    "methods": function () {},
    "functions": function () {},
    "extend": function () {},
    "defaults": function () {},
    "clone": function () {},
    "tap": function () {},
    "isEqual": function () {},
    "isEmpty": function () {},
    "isElement": function () {},
    "isArray": function () {},
    "isObject": function () {},
    "isArguments": function () {},
    "isFunction": function () {},
    "isString": function () {},
    "isNumber": function () {},
    "isNaN": function () {},
    "isBoolean": function () {},
    "isDate": function () {},
    "isRegExp": function () {},
    "isNull": function () {},
    "isUndefined": function () {},
    "has": function () {},
    "noConflict": function () {},
    "identity": function () {},
    "times": function () {},
    "escape": function () {},
    "mixin": function () {},
    "uniqueId": function () {},
    "templateSettings": {
        "evaluate": function () {},
        "interpolate": function () {},
        "escape": function () {}
    },
    "template": function () {},
    "chain": function () {}
}
