#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.getchef.com/api/v1'

cookbook 'ack'
cookbook 'apache2'
cookbook 'emacs'
cookbook 'git'
cookbook 'java'
cookbook 'lein'
cookbook 'mongodb'
cookbook 'nginx'
cookbook 'nginx-proxy'
cookbook 'nodejs'
cookbook 'ssl_certificate'
