FROM registry.kronkltd.net/kronkltd/jiksnu:${BRANCH_TAG:-latest}-dev

MAINTAINER Daniel E. Renfer <duck@kronkltd.net>

### Bootstrap project
ADD project.clj package.json \${JIKSNU_HOME}/

ADD script \${JIKSNU_HOME}/script

RUN script/update

### Add application
ADD . \${JIKSNU_HOME}/

### Set start script
CMD [ "script/entrypoint-run"]
