(ns jiksnu.actions.user-actions-test
  (:use (ciste [core :only [with-context]]
               [debug :only [spy]])
        (ciste.sections [default :only [show-section]])
        (clj-factory [core :only [factory fseq]])
        midje.sweet
        (jiksnu [test-helper :only [test-environment-fixture]])
        jiksnu.actions.user-actions)
  (:require (jiksnu.model [domain :as model.domain]
                          [user :as model.user]))
  (:import jiksnu.model.Domain
           jiksnu.model.User
           org.apache.abdera2.model.Person))

(test-environment-fixture

 (fact "#'get-domain"
   (fact "when the domain already exists"

     (let [domain (model.domain/create (factory Domain))]

       (fact "when the domain is specified"
         (let [response (get-domain {:domain (:_id domain)})]
           response => (partial instance? Domain)
           (:_id response) => (:_id domain)))

       (fact "when the domain is not specified"
         (fact "when there is an id"

           (fact "when it is a http url"
             (let [response (get-domain {:id (str "http://" (:_id domain) "/users/1")})]
               response => (partial instance? Domain)
               (:_id response) => (:_id domain)))

           (fact "when it is an acct uri"
             (let [response (get-domain {:id (str "acct:" (fseq :username) "@" (:_id domain))})]
               response => (partial instance? Domain)
               (:_id response) => (:_id domain))))))))

 (fact "#'create"
   (fact "when the params ar nil"
     (fact "should throw an exception"
       (create nil) => (throws RuntimeException))))


 (fact "#'person->user"
   (fact "when given a Person generated by show-section"
     (let [user (create (factory User))
           person (with-context [:http :atom] (show-section user))
           response (person->user person)]

       response => (partial instance? User)
       (:username response) => (:username user)
       (:id response) => (:id user)
       (:domain response) => (:domain user))))

 )
