(ns jiksnu.namespace
  (:refer-clojure :exclude (atom)))

(def as            "http://activitystrea.ms/spec/1.0/")
(def atom          "http://www.w3.org/2005/Atom")
(def dc            "http://purl.org/dc/elements/1.1/")
(def event         "http://jabber.org/protocol/pubsub#event")
(def everyone      "http://onesocialweb.org/spec/1.0/acl/subject/everyone")
(def foaf          "http://xmlns.com/foaf/0.1/")
(def grant         "http://onesocialweb.org/spec/1.0/acl/permission/grant")
(def host-meta     "http://host-meta.net/xrd/1.0")
(def inbox         "http://onesocialweb.org/spec/1.0/inbox")
(def microblog     "urn:xmpp:microblog:0")
(def osw           "http://onesocialweb.org/spec/1.0/")
(def person        "http://activitystrea.ms/schema/1.0/person")
(def poco          "http://portablecontacts.net/spec/1.0")
(def post          "http://activitystrea.ms/schema/1.0/post")
(def pubsub        "http://jabber.org/protocol/pubsub")
(def sioc          "http://rdfs.org/sioc/ns#")
(def status        "http://activitystrea.ms/schema/1.0/status")
(def thr           "http://purl.org/syndication/thread/1.0")
(def vcard         "urn:ietf:params:xml:ns:vcard-4.0")
(def vcard-publish "http://onesocialweb.org/spec/1.0/vcard4#publish")
(def vcard-query   "http://onesocialweb.org/spec/1.0/vcard4#query")
(def view          "http://onesocialweb.org/spec/1.0/acl/action/view")
(def xrd           "http://docs.oasis-open.org/ns/xri/xrd-1.0")
