{:site {:name "Renfer.name", :email nil},
 :htmlOnly false,
 :admins ["daniel"],
 :print
 {:actions true,
  :triggers true,
  :packet true,
  :routes true,
  :request false,
  :matchers false},
 :registration-enabled false,
 :jiksnu.plugins.google-analytics/account-id "UA-93750-5",
 :xmpp {:c2s [5222 5235], :s2s [5269 5275]},
 :airbrake {:enabled true},
 :http {:port 8082},
 :database {:name "renfer_name"},
 :domain "renfer.name"}
