#!/usr/bin/env bash

# Wait until all required external services have been initialized and are available

set -e

MAX_TRIES=${MAX_TRIES:-15}
COUNTER=0

. script/set-defaults

echo ">> Waiting for external services"

until script/check-connections || [ ${COUNTER} -eq ${MAX_TRIES} ]; do
    echo "Waiting on connections. n=${COUNTER}"
    sleep $(( COUNTER++ ))
done

if [ ${COUNTER} -eq ${MAX_TRIES} ]; then
  exit 1
fi

echo ". connected"
