#!/usr/bin/env bash

# Ensure that all required dependencies are available.
# This command is invoked by other top-level commands.

set -e

cd "$(dirname "$0")/.."

echo ">> Updating java dependencies"
lein deps

echo ">> Updating javascript dependencies"
npm update -q --dev
