#!/usr/bin/env bash

# Ensure that all required operations that do not rely on external services have been performed.
# This command is typically invoked by other top-level commands. (eg. update)

set -e

cd "$(dirname "$0")/.."

script/gather-dependencies
script/update-webdriver
script/compile
