#!/bin/sh

set -ex
set -x

docker build -t kronkltd/jiksnu-dev -f docker/web-dev/Dockerfile .
# docker build -t kronkltd/jiksnu-ruby-base docker/jiksnu-ruby-base/
docker-compose build web
docker-compose build web-dev
