#!/usr/bin/env bash

# Build the docker image(s) for this project.
# This command should be run from a docker host

set -e

cd "$(dirname "$0")/.."

command -v docker >/dev/null 2>&1 || { \
    echo >&2 "Docker is not available. This command should be run from outside a container."; \
    exit 1; \
}

. script/set-defaults

script/pull-docker

echo ">> Building New Image(s)"
echo "- ${DEV_IMAGE_TAG?}"
docker build -t ${DEV_IMAGE_TAG?} .

if [ -f "jiksnu.jar" ]; then
  echo "- ${IMAGE_TAG?}"
  docker build -t ${IMAGE_TAG?} -f Dockerfile.run .
else
  echo >&2 "Production jar not found. Skipping production build. Run script/compile"
fi
