#!/usr/bin/env bash

# Verify that all external services are available
# This command is invoked by other top-level commands.

set -e

cd "$(dirname "$0")/.."

command -v nc >/dev/null 2>&1 || { \
  echo >&2 "netcat is not available. This command should be run from inside a container."; \
  exit 1; \
}

. script/set-defaults

nc -z ${JIKSNU_DB_HOST?} ${JIKSNU_DB_PORT?} 2>/dev/null || \
  (echo "Unable to contact MongoDB server at ${JIKSNU_DB_HOST?}:${JIKSNU_DB_PORT?}"; exit 1)
