#!/usr/bin/env bash

# Verify that all external services are available
# This command is invoked by other top-level commands.

set -e

cd "$(dirname "$0")/.."

command -v nc >/dev/null 2>&1 || { \
  echo >&2 "netcat is not available. This command should be run from inside a container."; \
  exit 1; \
}

[ -z "${JIKSNU_DB_HOST}" ] && (\
    >&2 echo "Environment variable JIKSNU_DB_HOST has not been defined"; \
    exit 1)

nc -z ${JIKSNU_DB_HOST?} 27017 2>/dev/null || \
  (echo "Unable to contact MongoDB server at ${JIKSNU_DB_HOST?}"; \
   exit 1)
