#!/usr/bin/env bash

# Compile all clojure code and build production jars

set -e

echo ">> Compiling Clojure code"
lein install

echo ">> Building production jar"
lein with-profile +production,+test uberjar
cp -f target/jiksnu-*-standalone.jar jiksnu.jar
