#!/usr/bin/env bash

set -e

echo ">> Compiling CLJS"
lein with-profile +e2e,+test cljsbuild once
# lein cljsbuild once

echo ">> Gathering Client JS libraries"
./node_modules/.bin/browserify \
  main.js \
  -o target/resources/public/main.js \
  -t [ envify purge ]
