#!/bin/sh

set -ex

SENTRY_OPTS=""

if [ "$JIKSNU_SENTRY_DSN" ]; then
  SENTRY_OPTS="$SENTRY_OPTS -e JIKSNU_SENTRY_DSN=$JIKSNU_SENTRY_DSN"
fi

if [ "$JIKSNU_SENTRY_DSN_CLIENT" ]; then
  SENTRY_OPTS="$SENTRY_OPTS -e JIKSNU_SENTRY_DSN_CLIENT=$JIKSNU_SENTRY_DSN_CLIENT"
fi

docker-compose up -d mongo

docker rm -f jiksnu-dev || true

docker run \
  --rm \
  --name jiksnu-dev \
  -it \
  --net jiksnu_default \
  -v ${PWD}:/app \
  -v jiksnu-dev-media:/data \
  -e CISTE_LOGGER=jiksnu.logger \
  -e DOMAIN=dev.jiksnu.com \
  $SENTRY_OPTS \
  -p 8081:8080 \
  -p 7888:7888 \
  -p 9876:9876 \
  kronkltd/jiksnu-dev \
  script/byobu
