#!/usr/bin/env bash

set -e

INHERITED_OPTS=""

if [ "$JIKSNU_SENTRY_DSN" ]; then
  INHERITED_OPTS="$INHERITED_OPTS -e JIKSNU_SENTRY_DSN=$JIKSNU_SENTRY_DSN"
fi

if [ "$JIKSNU_SENTRY_DSN_CLIENT" ]; then
  INHERITED_OPTS="$INHERITED_OPTS -e JIKSNU_SENTRY_DSN_CLIENT=$JIKSNU_SENTRY_DSN_CLIENT"
fi

if [ "$JIKSNU_THEME_COLOR" ]; then
  INHERITED_OPTS="$INHERITED_OPTS -e JIKSNU_THEME_COLOR=$JIKSNU_THEME_COLOR"
fi

if [ "$NOTIFY_SEND_URL" ]; then
  INHERITED_OPTS="$INHERITED_OPTS -e NOTIFY_SEND_URL=$NOTIFY_SEND_URL"
fi

docker-compose up -d mongo

docker rm -f jiksnu-dev || true

docker run \
  --rm \
  --name jiksnu-dev \
  -it \
  --net jiksnu_default \
  -v ${PWD}:/app \
  -v jiksnu-dev-media:/data \
  -e CISTE_LOGGER=jiksnu.logger \
  -e DOMAIN=dev.jiksnu.com \
  $INHERITED_OPTS \
  -p 8081:8080 \
  -p 7888:7888 \
  -p 9876:9876 \
  registry.kronkltd.net/kronkltd/jiksnu-dev \
  script/byobu
