#!/bin/sh

if nc -z "elk" 9200 2>/dev/null; then
  curl -XPUT 'http://elk:9200/_template/filebeat?pretty' -d@/etc/filebeat/filebeat.template.json
  /etc/init.d/filebeat start
else
    echo "WARN: Logging service not available"
fi

lein with-profile +uberjar run
