#!/usr/bin/env bash

# Launch a byobu session with common development processes pre-loaded
# This command is invoked by the script/dev command. And should not be run directly.

. script/set-defaults

script/update

byobu new-session -d -s dev

# Add additional commands here
byobu new-window -t dev:1 -n "Server" "UPDATED=1 script/server; bash"
byobu new-window -t dev:2 -n "cljs"   "UPDATED=1 script/watch-cljs; bash"
byobu new-window -t dev:3 -n "karma"  "UPDATED=1 script/watch-karma; bash"

byobu select-window -t dev:1

byobu -2 attach-session -t dev
