#!/bin/sh

set -e

script/bootstrap

echo ">> Compiling Less"
lein less once

echo ">> Compiling CLJS"
lein with-profile +e2e,+test cljsbuild once
# lein cljsbuild once

lein compile
script/browserify
