#!/bin/sh

cd resources/public
# cljsc ../src/main/clojurescript '{:output-dir "public/cljs" :optimizations :advanced}' > cljs.js
cljsc ../../src/main/clojurescript '{:output-dir "cljs"}' > cljs/bootstrap.js
cd ..
