#!/bin/sh

cd resources/public
# cljsc ../resources/clojurescript '{:output-dir "public/cljs" :optimizations :advanced}' > cljs.js
cljsc ../../resources/clojurescript '{:output-dir "cljs"}' > cljs/bootstrap.js
cd ..
