{:tag :iq,
 :attrs {:type "set",
         :from "daniel@renfer.name/dell",
         :to "daniel@renfer.name",
         :id "osw1"},
 :content [{:tag :pubsub,
            :attrs {:xmlns "http://jabber.org/protocol/pubsub"},
            :content [{:tag :publish,
                       :attrs {:node "urn:xmpp:microblog:0"},
                       :content [{:tag :item,
                                  :attrs nil,
                                  :content [{:tag :entry,
                                             :attrs {:xmlns "http://www.w3.org/2005/Atom",
                                                     :xmlns:activity "http://activitystrea.ms/spec/1.0/",
                                                     :xmlns:osw "http://onesocialweb.org/spec/1.0/"},
                                             :content [{:tag :title,
                                                        :attrs nil,
                                                        :content ["to be or not to be ?"]}
                                                       {:tag :activity:verb,
                                                        :attrs nil,
                                                        :content ["http://activitystrea.ms/schema/1.0/post"]}
                                                       {:tag :activity:object,
                                                        :attrs nil,
                                                        :content [{:tag :activity:object-type,
                                                                   :attrs nil,
                                                                   :content ["http://onesocialweb.org/spec/1.0/object/status"]}
                                                                  {:tag :content,
                                                                   :attrs {:type "text/plain"},
                                                                   :content ["to be or not to be ?"]}]}
                                                       {:tag :osw:acl-rule,
                                                        :attrs nil,
                                                        :content [{:tag :osw:acl-action,
                                                                   :attrs {:permission "http://onesocialweb.org/spec/1.0/acl/permission/grant"},
                                                                   :content ["\n              http://onesocialweb.org/spec/1.0/acl/action/view\n            "]}
                                                                  {:tag :osw:acl-subject,
                                                                   :attrs {:type "http://onesocialweb.org/spec/1.0/acl/subject/everyone"},
                                                                   :content nil}]}]}]}]}]}]}
